function skillsmembers() {
    var skills = [
        { name: 'HTML', description: 'Hyper Text Markup Language' },
        { name: 'CSS', description: 'Cascading Style Sheets' },
        { name: 'JavaScript', description: 'JavaScript' },
        { name: 'Node.js', description: 'Node.js' },
        { name: 'React', description: 'React' },
        { name: 'Vue', description: 'Vue' },
        { name: 'Angular', description: 'Angular' },
        { name: 'MongoDB', description: 'MongoDB' },
        { name: 'MySQL', description: 'MySQL' },
        { name: 'PostgreSQL', description: 'PostgreSQL' },
        { name: 'Docker', description: 'Docker' },
        { name: 'Kubernetes', description: 'Kubernetes' },
        { name: 'AWS', description: 'Amazon Web Services' },
        { name: 'Azure', description: 'Azure' },
        { name: 'GCP', description: 'Google Cloud Platform' },
        { name: 'Jenkins', description: 'Jenkins' },
        { name: 'GitLab', description: 'GitLab' },
        { name: 'GitHub', description: 'GitHub' },
        { name: 'Git', description: 'Git' },
        { name: 'Python', description: 'Python' },
        { name: 'Java', description: 'Java' },
        { name: 'C++', description: 'C++' },
        { name: 'C#', description: 'C#' },
        { name: 'Ruby', description: 'Ruby' },
        { name: 'PHP', description: 'PHP' },
        { name: 'Swift', description: 'Swift' },
        { name: 'Kotlin', description: 'Kotlin' },
        { name: 'TypeScript', description: 'TypeScript' },
        { name: 'Rust', description: 'Rust' },
        { name: 'Scala', description: 'Scala' },
        { name: 'Go', description: 'Go' },
        { name: 'R', description: 'R' },
        { name: 'Haskell', description: 'Haskell' },
        { name: 'Erlang', description: 'Erlang' },
        { name: 'F#', description: 'final sharp' },
    ]
}